# Generated by Django 3.2.9 on 2021-11-21 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagemodel_custom_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='custom_thumbnail',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
