# Generated by Django 3.2.9 on 2021-11-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagemodel_custom_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='thumbnail200',
            new_name='thumbnail',
        ),
    ]
