# Generated by Django 3.2.9 on 2021-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_thumbnail200_imagemodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail400',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
